### ISSUE TITLE
Thumbnails not displaying for "long" videos

### ISSUE THREAD

**Issue by hgshoggins** [blacktrash/videojs-sprite-thumbnails#2]
Can't really find the real point where a video is a "long" one, but when video length exceeds a certain time, the tooltip usually containing the thumbnail is empty.

When inspecting the element, one can see that the image resource is correctly loaded, and that the expected size of the background is correct, but the background position is not updated at all when moving the mouse over the progress bar.

With the exact same usage of this plugin for shorter videos, there is no issue, and everything works like a charm.

Hereafter, with a "long" video and a "normal" one:
![Capture d’écran de 2019-05-31 23-20-25](https://user-images.githubusercontent.com/10128113/58735469-cc0d5800-83fa-11e9-8d13-5f4585bc6ece.png) ![Capture d’écran de 2019-05-31 23-18-08](https://user-images.githubusercontent.com/10128113/58735390-89e41680-83fa-11e9-928b-99f8d7677f9a.png)

I'm using the latest `video.js@7.4.5` along with `videojs-sprite-thumbnails@0.5.2` from npm.

A working video: [https://radiom.fr/s/v38](https://radiom.fr/s/v38)
... and a failing one: [https://radiom.fr/s/v39](https://radiom.fr/s/v39)

**Comment by blacktrash** [comment]
At a quick glance there's something fishy with the duration display in the controlbar at https://radiom.fr/s/v39. It says the video is 1:15:00 long, i.e., 4500 seconds, which is also roughly the duration you cater for with your thumbs: 72160px / 160px * 10 secs = 4510. However, the video has only a duration of
```js
videojs.getAllPlayers()[0].duration()
2767.8
```
Confirmed by:
```
ffprobe -v error -show_entries format=duration https://www.radiom.fr/media-rockinspace-okoyome.mp4
[FORMAT]
duration=2767.800000
[/FORMAT]
```

**Comment by hgshoggins** [comment]
Actually, the "okoyome" video belongs to the first URL (the working one), and has
```javascript
videojs.getAllPlayers()[0].duration()
2767.8
```
`ffprobe` sees `duration=2767.800000`
Sprite image is `44320x90`

whereas the "dyinggiants" one (the failing one) has
```javascript
videojs.getAllPlayers()[0].duration()
4500.630702
```
`ffprobe` sees `duration=4500.631000`
Sprite image is `72160x90`

... which seems consistent, except that the last one seems off by one sprite sample (the image represents `4510` seconds instead of `4500`. Could there be an issue here?

**Comment by blacktrash** [comment]
There is indeed a problem with the plugin. I'll look into it as soon as I can.

**Comment by blacktrash** [comment]
Hm, looks like a blamed the plugin to early because I misconfigured my test case ;-)
Here's a sample which works just fine: https://blacktrash.org/test/videojs/sprite-thumbnails-2.html - duration 1:51:33

I'll try and play around with your video/thumbs combo when I find time.

**Comment by blacktrash** [comment]
Actually I see the problem only in Firefox so far. Chrome and Safari work (on Mac).

![spritethumb2](https://user-images.githubusercontent.com/168338/58747677-c5b8c380-846e-11e9-970e-898f88b8db7a.jpg)

I speculate that the PNG dimensions may cause probs in some browsers. At least you can't create JPEGs of that width (max 65500). So pragmatically maybe create a sprite with more than 1 row? [This generator](https://github.com/flavioribeiro/video-thumbnail-generator) works for me[tm].

**Comment by hgshoggins** [comment]
Thank you!
I've just created a multi-row sprite, limiting the width of the total image to `30400px` (just a multiple of `160` easier to handle), and now I'm not sure how the plugin should work with such an image, should I specify something else in the params?

**Comment by hgshoggins** [comment]
Works like a charm, thanks!

**Comment by blacktrash** [comment]
> I've just created a multi-row sprite, limiting the width of the total image to `30400px` (just a multiple of `160` easier to handle), and now I'm not sure how the plugin should work with such an image, should I specify something else in the params?

No, no further config needed. One goal of the plugin is ease of configuration. It detects the sprite's dimensions and determines the amount of rows and columns on its own.
