### ISSUE TITLE
Recommended method for creating sprite image

### ISSUE THREAD

**Issue by pipdig** [blacktrash/videojs-sprite-thumbnails#8]
Hi there!

I was wondering if there is a recommended method for generating the sprite image to work best with this plugin? Something like https://askubuntu.com/questions/377579/how-can-i-use-ffmpeg-to-output-a-screenshot-gallery-mosaic/377630#377630 perhaps?

Thanks

**Comment by blacktrash** [comment]
@pipdig - no particular recommendation, anything that does the job for you.

FWIW, I use [video-thumbnail-generator](https://github.com/flavioribeiro/video-thumbnail-generator). I considered looking into an ffmpeg-only way, but so far was too lazy ;-)
